[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["Edward <73746306+WangEdward@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
